label: Lists
status: ready
preview: '@dkwds-framed'

context:
  list_example:
    items:
      - listitem: Unordered list item
      - listitem: Unordered list item
      - listitem: Unordered list item
