label: Alerts
status: ready
preview: '@dkwds-framed'
context:
  alert_example:
    content: "Lorem ipsum dolor sit amet, <a href=\"javascript:void(0);\">consectetur adipiscing</a> elit, sed do eiusmod."

variants:
  - name: default
    label: Info
    context:
      alert_example:
        classes: "alert-info"
        title: Information Status

  - name: info
    label: Success
    context:
      alert_example:
        classes: "alert-success"
        title: Success Status


  - name: warning
    label: Warning
    context:
      alert_example:
        classes: "alert-warning"
        title: Warning Status

  - name: error
    label: Error
    context:
      alert_example:
        classes: "alert-error"
        title: Error Status
        role: "alert"

  - name: paragraph
    label: Paragraph
    context:
      alert_example:
        classes: " alert-info alert-paragraph"
        title: Information Status - Paragraph Width
        content: "Multi line. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui atione voluptatem sequi nesciunt. Neque porro quisquam est, qui doloremipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

  - name: no-header
    label: No header
    context:
      alert_example:
        classes: " alert-info"
        content: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."

  - name: slim
    label: Slim
    context:
      alert_example:
        classes: "alert-info alert-slim"
        content: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
