label: Alerts
status: ready
preview: '@dkwds-framed'
context:
  alert_example:
    items:
      - name: info
        classes: "alert-info"
        role: "alert"
        title: "Information alert"
        content: "Multi line. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui atione voluptatem sequi nesciunt. Neque porro quisquam est, qui doloremipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

      - name: success
        classes: "alert-success"
        role: "alert"
        title: Success alert
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
            
      - name: warning
        classes: "alert-warning"
        role: "alert"
        title: Warning alert
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."

      - name: error
        classes: "alert-error"
        role: "alert"
        title: Error alert
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        
      - name: info with icon
        classes: "alert-info alert--show-icon"
        role: "alert"
        title: "Information alert - with icon"
        content: "Multi line. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui atione voluptatem sequi nesciunt. Neque porro quisquam est, qui doloremipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

      - name: success with icon
        classes: "alert-success alert--show-icon"
        role: "alert"
        title: "Success alert - with icon"
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
            
      - name: warning with icon
        classes: "alert-warning alert--show-icon"
        role: "alert"
        title: "Warning alert - with icon"
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."

      - name: error with icon
        classes: "alert-error alert--show-icon"
        role: "alert"
        title: "Error alert - with icon"
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
      
      - name: info no text
        classes: "alert-info alert--show-icon"
        role: "alert"
        title: "Information alert - heading only"

      - name: Info paragraph
        classes: "alert-info alert--paragraph"
        role: "alert"
        title: Info paragraph
        content: "Multi line. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui atione voluptatem sequi nesciunt. Neque porro quisquam est, qui doloremipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."