label: Labels
status: ready
preview: '@dkwds-framed'

variants:
  - name: default
    label: Info
    context:
      label:
        classes: ""

  - name: big
    label: Big
    context:
      label:
        classes: "usa-label-big"
