label: Tab navigation
status: ready
preview: '@dkwds-framed'

context:
  tabnavlist:
    items: &default_links
      - title: tabnav 1
      - title: tabnav 2 (valgt)
        active: true
      - title: tabnav 3
      - title: tabnav 4
      - title: tabnav 5