label: Tringuide
status: ready

context:
  tringuiden:
    trinlisten: &default_links
      - text: Trin 1
        icon: check
      - text: Trin 2
        icon: check
      - text: Trin 3 (valgt)
        current: true
      - text: Trin 4
      - text: Trin 5



