label: Headers
status: ready

context:
  portal_header_data:
    title: Portal Header from config
    id_prefix: basic-
    link: 
      - title: Distinct from each other
        href: 'javascript:void(0);'
        label: label
  solution_header_data:
    title: Solution Header from config
    id_prefix: basic-
    link: 
      - title: Distinct from each other
        href: 'javascript:void(0);'
        label: label
  solution_nav:
    search: false
    links:
      - text: Secondary priority link
        class: button button-primary
      - text: Easy to comprehend link
  top_nav:
    search: false
    id_prefix: extended-mega-
    mega: true
    links:
      - text: Section title
        id: nav-section-one
        links: &subnav_links
          - text: Subsection title
            href: '#'
          - text: Subsection title
            href: '#'
          - text: Subsection title
            href: '#'
          - text: Subsection title longer
            href: '#'
          - text: A very long page title that goes onto two lines
            href: '#'
          - text: Subsection title
            href: '#'
          - text: Subsection title
            href: '#'
          - text: Subsection title
            href: '#'
          - text: Subsection title
            href: '#'
      - text: Simple terms
        id: nav-section-two
        links: *subnav_links
      - text: Distinct from each other
        href: 'javascript:void(0)'
  top_nav_buttons:
    links:
      - text: Secondary priority link
        type: link
      - text: Easy to comprehend
        type: button
      - text: Dropdown
        type: dropdown

variants:
  - name: default
    label: Compare
    status: null

  - name: basic
    label: Basic header
    context:
      header:
        primary:
          search: true
          id_prefix: basic-

  - name: basic-mega
    label: Basic with mega-menu
    context:
      header:
        primary:
          search: true
          id_prefix: basic-mega-
          mega: true

  - name: extended
    label: Extended header
    context:
      header:
        primary:
          search: false
          id_prefix: extended-
        secondary:
          search: true

  - name: extended-mega
    label: Extended with mega-menu
    context:
      header:
        primary:
          search: false
          id_prefix: extended-mega-
          mega: true
        secondary:
          search: true
