label: Modal
status: ready
preview: '@dkwds-framed'

context:
  modalpassive_example:
    items:
      - type: "passive"
        close: 'Luk'
        title: 'Modaltitel for passiv modal'
        description: 'Beskrivelse af den passive modals inhold'
  modalinteractive_example:
    items:
      - type: "interactive"
        close: 'Luk'
        title: 'Modaltitel for interaktiv modal'
        description: 'Beskrivelse af den interaktive modals inhold'