label: Tags
status: ready
preview: '@dkwds-framed'

variants:
  - name: default
    label: Examples


context:
  tag_example:
    items:
      - class: 'primary'
        label: 'Tags'
        state: 'default'
      - class: 'primary'
        state: 'hover'
      - class: 'primary'
        state: 'active'
      - class: 'primary'
        state: 'focus'
      - class: 'primary'
        state: 'disabled'

      - class: 'secondary'
        label: 'Tags with icons'
        state: 'default'
      - class: 'secondary'
        state: 'hover'
      - class: 'secondary'
        state: 'active'
      - class: 'secondary'
        state: 'focus'
      - class: 'secondary'
        state: 'disabled'

      - class: 'primary'
        label: 'Button with icon'
        state: 'icon'
