label: Icons
status: ready
preview: '@dkwds-framed'

context:
  icons_example:
    items:
      - icon: book-open-variant
      - icon: telegram
      - icon: account
      - icon: account-card-details
      - icon: chart-bar
      - icon: minus-circle
      - icon: barcode
      - icon: chart-areaspline
      - icon: ear-hearing
      - icon: anchor
      - icon: calendar-check
      - icon: checkbox-marked
      - icon: human-child
      - icon: file-xml
      - icon: clipboard-text
      - icon: account-multiple-plus
