label: Checkbox
status: ready
preview: '@dkwds-framed'

context:
  checkbox_example:
    items:
      - id: Unchecked
        name: unchecked
        value: unchecked
        checked: false
        disabled: false
        text: unchecked

      - id: Checked
        name: checked
        value: checked
        checked: true
        disabled: false
        text: checked

      - id: disabled
        name: disabled
        value: disabled
        checked: false
        disabled: true
        text: Disabled

      - id: fokus
        name: Focus
        value: fokus
        checked: false
        disabled: false
        text: Focus
        class: focus
