label: Dato-input
status: ready
preview: '@dkwds-framed'

context:
  datoinput_example:
    items:
      - label: Indsendelsesfrist
        hint: "For eksempel: 05 12 2018"
        day: "Day"
        month: "Måned"
        year: "År"
    