label: Radio button
status: ready
preview: '@dkwds-framed'

context:
  radiobuttons_example:
    items:
      - id: truth
        name: historical-figures-1
        value: truth
        text: Sojourner Truth
        checked: false
        disabled: false

      - id: douglass
        name: historical-figures-1
        value: douglass
        text: Frederick Douglass
        checked: true
        disabled: false

      - id: washington
        name: historical-figures-1
        value: washington
        text: Booker T. Washington
        checked: false
        disabled: true

      - id: carver
        name: historical-figures-1
        value: carver
        text: George Washington Carver
        checked: false
        disabled: false
        focus: true

      - id: truth-large
        name: historical-figures-1-large
        value: truth-large
        text: Sojourner Truth
        checked: false
        disabled: false
        large: true

      - id: douglass-large
        name: historical-figures-1-large
        value: douglass-large
        text: Frederick Douglass
        checked: true
        disabled: false
        large: true

      - id: washington-large
        name: historical-figures-1-large
        value: washington-large
        text: Booker T. Washington
        checked: false
        disabled: true
        large: true

      - id: carver-large
        name: historical-figures-1-large
        value: carver-large
        text: George Washington Carver
        checked: false
        disabled: false
        focus: true
        large: true