label: Tekst-area
status: ready
preview: '@dkwds-framed'

context:
  textarea_example:
    items:
      - id: input-area
        label: Text area label
        name: input-area
      - id: input-error
        label: Text area error
        name: input-area
        error: Hjælpsom error besked
