label: Tekst-input width
status: ready
preview: '@dkwds-framed'

context:
  textinputwidth_example:
    items:
      - id: input-type-text-xxs
        label: Tekst input med bredde på 5.5rem
        name: input-type-text-xxs
        class: input-width-xxs
      - id: input-type-text-xs
        label: Tekst input med bredde på 10rem
        name: input-type-text-xs
        class: input-width-xs
      - id: input-type-text-s
        label: Tekst input med bredde på 15rem
        name: input-type-text-s
        class: input-width-s
      - id: input-type-text-m
        label: Tekst input med bredde på 20rem
        name: input-type-text-m
        class: input-width-m
      - id: input-type-text-l
        label: Tekst input med bredde på 30rem
        name: input-type-text-l
        class: input-width-l
      - id: input-type-text-xl
        label: Tekst input med bredde på 40rem
        name: input-type-text-xl
        class: input-width-xl
      - id: input-type-text-xxl
        label: Tekst input med bredde på 50rem
        name: input-type-text-xxl
        class: input-width-xxl