label: Tekst-input
status: ready
preview: '@dkwds-framed'

context:
  textinput_example:
    items:
      - id: input-type-text
        label: Text input label
        name: input-type-text
        hint: For example, VO123456D
      - id: input-focus
        label: Text input focused
        class: focus
        name: input-focus
      - id: input-error
        name: input-error
        label: Text input error
        error: Helpful error message
        hint: For example, VO123456D
      - id: input-success
        label: Text input success
        success: true
