label: Search
status: ready
preview: '@dkwds-framed'

# variants:
#   - name: default
#     label: Example
#
# context:
#   label_example:
#     items:
#       - name: default
#         classes: ""
#         label: Normal
#
#       - name: big
#         classes: "usa-label-big"
#         label: Big
