label: Buttons
status: ready
preview: '@dkwds-framed'

variants:
  - name: default
    label: Examples


context:
  button_example:
    items:
      - class: 'primary'
        label: 'Primary buttons'
        state: 'default'
      - class: 'primary'
        state: 'hover'
      - class: 'primary'
        state: 'active'
      - class: 'primary'
        state: 'focus'
      - class: 'primary'
        state: 'disabled'
      - class: 'primary'
        state: 'icon'

      - class: 'secondary'
        label: 'Secondary buttons'
        state: 'default'
      - class: 'secondary'
        state: 'hover'
      - class: 'secondary'
        state: 'active'
      - class: 'secondary'
        state: 'focus'
      - class: 'secondary'
        state: 'disabled'

      - class: 'ghost'
        label: 'Ghost buttons'
        state: 'default'
      - class: 'ghost'
        state: 'hover'
      - class: 'ghost'
        state: 'active'
      - class: 'ghost'
        state: 'focus'
      - class: 'ghost'
        state: 'disabled'

      - class: 'tertiary'
        label: 'Tertiary buttons'
        state: 'default'
      - class: 'tertiary'
        state: 'hover'
      - class: 'tertiary'
        state: 'active'
      - class: 'tertiary'
        state: 'focus'
      - class: 'tertiary'
        state: 'disabled'
