label: Buttons
status: ready

variants:
  - name: primary
    context:
      category: primary
      label: Primary buttons
      classes: 'usa-button'

  - name: secondary
    context:
      category: secondary
      label: Secondary buttons
      classes: 'usa-button-secondary'

  - name: ghost
    context:
      category: ghost
      label: Ghost buttons
      classes: 'usa-button-ghost'

  - name: small
    context:
      category: small
      label: Small buttons
      classes: 'usa-button-small'
