label: Footer basic
status: ready
preview: '@dkwds-framed'

context:
  footerbasic_example:
    items:
      - size: "card-small"
        header: 'Header'
        subheader: 'Understøttende tekst'
        headercontent: 'Dette er et <em>content område</em>, hvor du kan skrive hvad du har lyst til.'