status: ready

context:
  footer_basic_data:
    cols:
      - col:
        col_size_desktop: 6
        text_align_right: false
        lists:
          - list:
            inline_list: true
            listitems:
              - content: '<span class="h5 weight-semibold">Undervisningsministeriet</span>'
              - content: '<p>Styrelsen for IT og læring</p>'
      - col:
        col_size_desktop: 6
        text_align_right: true
        lists:
          - list:
            inline_list: true
            listitems:
              - content: <a class="function-link" href="mailto:support@stil.dk">support@stil.dk</a>
              - content: <a class="function-link" href="tel:004533925200">(+45) 33 92 52 00</a>